# Generated by Django 5.2.3 on 2025-07-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('category', 'Category'), ('subcategory', 'Sub Category'), ('subsubcategory', 'Sub Sub Category')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
            ],
            options={
                'verbose_name': 'Sub Category',
                'verbose_name_plural': 'Sub Categories',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('virtual_model.category',),
        ),
        migrations.CreateModel(
            name='SubSubCategory',
            fields=[
            ],
            options={
                'verbose_name': 'Sub Sub Category',
                'verbose_name_plural': 'Sub Sub Categories',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('virtual_model.category',),
        ),
    ]
