# Generated by Django 5.2.3 on 2025-07-05 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Product', '0001_initial'),
        ('candidates', '0002_candidatedocument'),
        ('contact', '0006_alter_contact_whatsapp'),
        ('customer', '0009_customer_customer_name_364ac9_idx_and_more'),
        ('superadmin', '0004_superadmin_role'),
        ('virtual_model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('order_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.candidate')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_by_category', to='virtual_model.category')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.contact')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.product')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_by_subcategory', to='virtual_model.subcategory')),
                ('subsubcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_by_subsubcategory', to='virtual_model.subsubcategory')),
                ('superadmin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superadmin.superadmin')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'order',
                'ordering': ['-order_date'],
                'indexes': [models.Index(fields=['order_date'], name='order_order_d_858e02_idx'), models.Index(fields=['order_status'], name='order_order_s_15dbf1_idx'), models.Index(fields=['total_amount'], name='order_total_a_642cde_idx')],
                'unique_together': {('customer', 'order_date')},
            },
        ),
    ]
