# Generated by Django 5.2.3 on 2025-07-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
        ('candidates', '0002_candidatedocument'),
        ('contact', '0006_alter_contact_whatsapp'),
        ('customer', '0009_customer_customer_name_364ac9_idx_and_more'),
        ('master_com', '0001_initial'),
        ('superadmin', '0004_superadmin_role'),
        ('virtual_model', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer'], name='order_custome_7c3d15_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['superadmin'], name='order_superad_5ced28_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['candidate'], name='order_candida_d2fa74_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['contact'], name='order_contact_3c75a8_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['product'], name='order_product_beef32_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['category'], name='order_categor_fbbd0c_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['subcategory'], name='order_subcate_dc4a4a_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['subsubcategory'], name='order_subsubc_462dc9_idx'),
        ),
    ]
