# Generated by Django 5.1.3 on 2024-11-13 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('re_password', models.CharField(max_length=200)),
                ('otp', models.CharField(blank=True, max_length=4, null=True)),
                ('role', models.CharField(choices=[('Customer', 'Customer')], max_length=20)),
                ('Superadmin', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='superadmin.superadmin')),
            ],
            options={
                'db_table': 'customer',
            },
        ),
    ]
