# Generated by Django 5.2.3 on 2025-07-02 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_rename_first_name_customer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Superadmin',
            new_name='superadmin',
        ),
    ]
