# Generated by Django 5.2.3 on 2025-07-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_rename_superadmin_customer_superadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
