# Generated by Django 5.2.3 on 2025-07-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_customer_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='whatsapp',
            field=models.CharField(max_length=15),
        ),
    ]
