# Generated by Django 5.2.3 on 2025-07-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_alter_customer_whatsapp'),
        ('superadmin', '0004_superadmin_role'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['name'], name='customer_name_364ac9_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['last_name'], name='customer_last_na_195637_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['mobile'], name='customer_mobile_19f0d4_idx'),
        ),
    ]
