# Generated by Django 5.2.3 on 2025-07-04 09:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title_types', models.CharField(blank=True, choices=[('TOP_RATED', 'Top Rated Products'), ('NEW_ARRIVALS', 'New Arrivals'), ('BEST_SELLERS', 'Best Sellers'), ('Most Popular Products', 'Most Popular Products'), ('Trending Products', 'Trending Products')], max_length=50, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('in_stock', models.BooleanField(default=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('image', models.URLField()),
                ('model_3d', models.URLField()),
                ('size_tags', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('dfx_content', models.JSONField(blank=True, null=True)),
                ('section', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['title_types'], name='Product_pro_title_t_71b02b_idx'), models.Index(fields=['name'], name='Product_pro_name_026bf9_idx'), models.Index(fields=['gender'], name='Product_pro_gender_03b211_idx'), models.Index(fields=['section'], name='Product_pro_section_069552_idx')],
            },
        ),
    ]
