# Generated by Django 5.1.4 on 2024-12-20 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254)),
                ('Mobile', models.CharField(max_length=12)),
                ('Message', models.TextField()),
            ],
            options={
                'db_table': 'contact',
            },
        ),
    ]
