# Generated by Django 5.2.3 on 2025-07-02 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Message',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Mobile',
            new_name='mobile',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='created_at',
        ),
    ]
