# Generated by Django 5.2.3 on 2025-07-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_rename_email_contact_email_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['name'], name='contact_name_bf8f95_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['email'], name='contact_email_7a7031_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['mobile'], name='contact_mobile_be7f1f_idx'),
        ),
    ]
