# Generated by Django 5.2.3 on 2025-07-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_contact_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='whatsapp',
            field=models.CharField(max_length=15),
        ),
    ]
