# Generated by Django 5.2.3 on 2025-06-27 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='candidate_documents/')),
                ('doc_type', models.CharField(help_text='e.g. Resume, Certificate', max_length=50)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='candidates.candidate')),
            ],
            options={
                'verbose_name': 'Candidate Document',
                'verbose_name_plural': 'Candidate Documents',
                'ordering': ['candidate', 'doc_type'],
            },
        ),
    ]
