# Generated by Django 5.1.4 on 2024-12-11 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='superadmin',
            table='SuperAdmin',
        ),
    ]
