# Generated by Django 5.1.4 on 2024-12-11 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_alter_superadmin_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='superadmin',
            table='superadmin',
        ),
    ]
